Mark RAG vector embedding and prompt tests as optional (#540)
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -365,10 +365,11 @@ steps:
           exit 1
         fi
 
-        if [[ $(cat /workspace/rag_prompt_result.txt) != "pass" ]]; then
-          echo "rag frontend test failed"
-          exit 1
-        fi
+        # TODO: re-add this check once generating embeddings in CI is stable
+        # if [[ $(cat /workspace/rag_prompt_result.txt) != "pass" ]]; then
+        #   echo "rag frontend test failed"
+        #   exit 1
+        # fi
 
     waitFor: ['cleanup gke cluster']
         
