add kueue for nccl tests

diff --git a/applications/hcc/modules/nemo/helm-charts/nccl-tests/templates/ultra-test.yaml b/applications/hcc/modules/nemo/helm-charts/nccl-tests/templates/ultra-test.yaml
--- a/applications/hcc/modules/nemo/helm-charts/nccl-tests/templates/ultra-test.yaml
+++ b/applications/hcc/modules/nemo/helm-charts/nccl-tests/templates/ultra-test.yaml
@@ -5,6 +5,9 @@ apiVersion: jobset.x-k8s.io/v1alpha2
 kind: JobSet
 metadata:
   name: nccl-test
+  namespace: default
+  labels:
+    kueue.x-k8s.io/queue-name: a3-kueue-user-queue
 spec:
   ttlSecondsAfterFinished: 1200
   suspend: False
@@ -19,6 +22,7 @@ spec:
           template:
             metadata:
               annotations:
+                kueue.x-k8s.io/podset-preferred-topology: "kubernetes.io/hostname"
                 "helm.sh/hook": post-install
                 "helm.sh/hook-weight": "1" 
                 "helm.sh/hook-delete-policy": hook-succeeded
@@ -40,7 +44,7 @@ spec:
               activeDeadlineSeconds: 3600
               restartPolicy: Never
               nodeSelector:
-                cloud.google.com/gke-accelerator: nvidia-h200-141gb
+                cloud.google.com/gke-nodepool: a3-ultragpu-8g-a3-ultragpu-pool
               tolerations:
               - key: cloud.google.com/gke-queued
                 effect: NoSchedule
@@ -68,10 +72,51 @@ spec:
                 emptyDir:
                   medium: "Memory"
                   sizeLimit: 250Gi
-              schedulingGates:
-              - name: "gke.io/topology-aware-auto-nccl-test"
+              - name: sys
+                hostPath:
+                  path: /sys
+              - name: proc-sys
+                hostPath:
+                  path: /proc/sys
+
+              # initContainers:
+              # - name: gpu-healthcheck
+              #   image: alpine:latest
+              #   command: ["/bin/sh", "-c"]
+              #   args:
+              #   - |
+              #     apk add --no-cache bash  # Install bash
+              #     /bin/bash -c "set -ex
+              #     NUM_GPUS=$(/usr/local/nvidia/bin/nvidia-smi --query-gpu=driver_version --format=csv,noheader,nounits | wc -l)
+              #     if [ \${NUM_GPUS} -lt 8 ]; then
+              #       echo \"Error: Only \${NUM_GPUS} GPUs and expected 8\"
+              #       exit 1
+              #     fi
+              #     gpu_errors=(\$(/usr/local/nvidia/bin/nvidia-smi --query-gpu=ecc.errors.uncorrected.volatile.total --format=csv,noheader,nounits))
+              #     for gpu_index in \${!gpu_errors[@]}; do
+              #         if [ \${gpu_errors[\$gpu_index]} == '[N/A]' ]; then
+              #             echo 'Error: ERR detected in GPU index '\$gpu_index
+              #             exit 1
+              #         elif [ \${gpu_errors[\$gpu_index]} -gt 0 ]; then
+              #             echo 'Error: Unrecoverable ECC errors detected in GPU index '\$gpu_index
+              #             exit 1
+              #         fi
+              #     done
+              #     echo \${NUM_GPUS} GPUs found with no ERR or Unrecoverable ECC errors"
+
+                # volumeMounts:
+                # - name: nvidia
+                #   mountPath: /usr/local/nvidia
+                # - name: lib64
+                #   mountPath: /lib64
+                # securityContext:
+                #   privileged: true
+                # env:
+                # - name: LD_LIBRARY_PATH
+                #   value: /usr/local/nvidia/lib64
+
               containers:
-              - name: nccl-test
+              - name: nccl
                 stdin: true
                 tty: true
                 image: us-docker.pkg.dev/gce-ai-infra/gpudirect-gib/nccl-plugin-gib-diagnostic:v1.0.3
@@ -100,11 +145,14 @@ spec:
                 - bash
                 - -c
                 - |
-
                   set -x
-
+                  export N_NODES=$N_NODES
                   echo "Starting workload container on ${MY_NODE_NAME} for $N_NODES benchmark"
-                  # # Install ping
+
+                  # Load all the cuda libs
+                  /sbin/ldconfig
+
+                  # Install ping
                   apt update -y
                   apt install -y iputils-ping
 
@@ -175,5 +223,4 @@ spec:
                     nvidia.com/gpu: 8
                   requests:
                     nvidia.com/gpu: 8
-              restartPolicy: Never
 {{- end }}
